### ISSUE TITLE
Obj-C Interop: `updateUI` block not called when value is `nil`

### ISSUE THREAD

**Issue by nonsensery** [Electrode-iOS/ELWebService#34]
In the objc interop code for ServiceTasks, [there is a type-check](https://github.com/Electrode-iOS/ELWebService/blob/master/Source/Core/ServiceTask%2BObjC.swift#L135) before the `updateUI` block is called:

```
if let value = value as? AnyObject {
    handler(value)
}
```

If `value` is `nil`, the check fails and the block is not called. I think it should be `value as? AnyObject?`.

**Comment by nonsensery** [comment]
Also, it might be nice if it did something other than fail silently when the type cannot be converted. Maybe it should even be more like:
```
handler(value as! AnyObject?)
```
so it would just crash in that case.

**Comment by nonsensery** [comment]
Note: added similar code in #32

**Comment by angelodipaolo** [comment]
Good catch. I agree it is better to avoid failing silently and instead crash fatally since this is an error you would want to find during development.
